### ISSUE TITLE
Unhandled error when NOT using MFA

### ISSUE THREAD

**Issue by Loosh64** [mijdavis2/pyokta-aws-cli-assume-role#10]
Install the code and create config file as prescribed in README. mfa_choice is omitted from profile in config and is not enabled on AWS role or login. Attempt to auth to that profile yields:

```
Traceback (most recent call last):
  File "%LOCALAPPDATA%\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "%LOCALAPPDATA%\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "%LOCALAPPDATA%\Programs\Python\Python37\Scripts\pyokta-aws.exe\__main__.py", line 9, in <module>
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\__main__.py", line 26, in main
    return dispatch(sys.argv[1:])
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\cli.py", line 69, in dispatch
    return main(args.args)
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\commands\auth.py", line 99, in main
    return authenticate(auth_settings)
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\commands\auth.py", line 70, in authenticate
    saml = okta.get_saml_via_auth()
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\okta\api.py", line 151, in get_saml_via_auth
    token = self._verify_via_mfa(resp.json())
  File "%LOCALAPPDATA%\programs\python\python37\lib\site-packages\pyokta_aws\okta\api.py", line 128, in _verify_via_mfa
    "Don't know how to handle status '{}'".format(data.get('status')))
Exception: Something went wrong.
Don't know how to handle status 'SUCCESS'
```
I have replaced the actual path in each line with the variable %LOCALAPPDATA% to keep things generic 8-) I've been playing around in the code and it appears that it tries to check MFA methods even when the option is omitted in the profile, plus there is that return value of "SUCCESS" that _verify_via_mfa is not expecting. Is this a bug, or am I doing something wrong?

**Comment by mijdavis2** [comment]
"No MFA" use case is not handled. So far this tool assumes at least one MFA option is enabled. I'll add this as a feature request. Thanks!

**Comment by Loosh64** [comment]
Thank you. Any idea when you might tackle that? We're interested in deploying this tool - or one like it - in a production environment. If you're busy with other priorities, I'll keep looking, or maybe take a stab at making the change myself.

**Comment by mijdavis2** [comment]
I _might_ be able to get to this by EOD this Sunday. Focus is on MFA enhancements as it's more secure and there's an internal requests for push notification support as well.

I _highly_ encourage enforcing MFA via your Okta org so this "just works" as is. 

(sorry for the late response; thanks for your interest!)
